-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghLw6Y83XzinNZSOT
sJQUEz4IbC0Tdd6fz8PCGqLAMEegCgYIKoZIzj0DAQehRANCAARlQF0y04eOhvDg
xsfjJDeaDgLiTQJh8USgdxxsr33LYhd/RyFbGy6zfGqfSfGY49qL93XIjFKMGW1g
vbBPlVpT
-----END PRIVATE KEY-----